# Actividad 2
print("")  # Imprime una línea en blanco
print("Emmanuel_Castruita_Soto 3W_1176")  # Imprime el nombre
print("")  # Imprime otra línea en blanco

# Define la función para saludar a una persona
def saludar(nombre):
    print(f"¡Hola {nombre}!")  # Imprime un saludo personalizado con el nombre proporcionado

# Ejemplo de uso de la función saludar
saludar("emmanuel")  # Llama a la función con el nombre "emmanuel"
