# Actividad 1
print("")  # Imprime una línea en blanco
print("Emmanuel_Castruita_Soto 3W_1176")  # Imprime el nombre 
print("")  # Imprime otra línea en blanco

# Define el saludo para luego imprimir el texto declarado
def mostrar_saludo():
    print("Hey amigos!")  # Imprime un saludo
    print("")  # Imprime una línea en blanco

mostrar_saludo()  # Llama a la función para mostrar el saludo